name: Build

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  Build:
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            gcc_arch: x86_64
          - os: ubuntu-22.04-arm
            gcc_arch: aarch64
    runs-on: ${{ matrix.os }}
    env:
      GCC_ARCH: ${{ matrix.gcc_arch }}
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: |
          ./build.sh

      - name: Release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: output/*
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          generateReleaseNotes: true
