name: Build

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          ./build.sh

      - name: Release
        uses: ncipollo/release-action@v1.11.2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: output/*
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          generateReleaseNotes: true
